[workspace]
authors = ["Andreas Chatzopoulos <andreas.chatzopoulos@gmail.com>"]
# channels = ["conda-forge"]
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch"]
name = "testdev"
# description = "Add a short description here"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
server = {cmd="uvicorn main:app --host=0.0.0.0 --port=8001 --reload"}

[dependencies]
fastapi = ">=0.115.12,<0.116"
python-dotenv = ">=1.1.0,<2"

[pypi-dependencies]
pydantic-ai-slim = { version = ">=0.1.6, <0.2", extras = ["openai"] }
# pylint = ">=3.3.6,<4"
